name: test-backend
on:
  # Pour commencer, vous voulez lancer ce travail sur les branches main et develop
  push:
    branches:
      main
      develop
  pull_request:
      
jobs:
  test-backend: 
    runs-on: ubuntu-22.04
    steps:
     #checkout your github code using actions/checkout@v2.5.0
      - uses: actions/checkout@v2.5.0

     #do the same with another action (actions/setup-java@v3) that enable to setup jdk 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

     #finally build your app with the latest command
      - name: Build and test with Maven
        #run: mvn -f ./backendAPI/pom.xml clean install
        run : mvn -B verify sonar:sonar -Dsonar.projectKey=nicooduc_TP_DevOps -Dsonar.organization=nicooduc-devops -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=${{ secrets.SONAR_TOKEN }}  --file ./backendAPI/pom.xml
