name: CI devops 2023
on:
  #to begin you want to launch this job in main and develop
  push:
    branches: #TODO 
  pull_request:

jobs:
  test-backend: 
    runs-on: ubuntu-22.04
    steps:
     #checkout your github code using actions/checkout@v2.5.0
      - uses: actions/checkout@v2.5.0

     #do the same with another action (actions/setup-java@v3) that enable to setup jdk 17
      - name: Set up JDK 17
        #TODO

     #finally build your app with the latest command
      - name: Build and test with Maven
        run: #TODO
